a=int(input('Nhap a='))
b=int(input('Nhap b='))
print('a+b=',eval("a+b"))
print('a-b=',eval("a-b"))
print('a*b=',eval("a*b"))
print('a/b=',eval("a/b"))
print('a%b=',eval("a%b"))
print('a^b=',eval("a**b"))